//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPID.AspNetCore.Authentication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPID.AspNetCore.Authentication.Resources.ErrorLocalization", typeof(ErrorLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticazione fallita per ripetuta sottomissione di credenziali errate (superato numero  tentativi secondo le policy adottate).
        /// </summary>
        public static string _19 {
            get {
                return ResourceManager.GetString("19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente privo di credenziali compatibili con il livello richiesto dal fornitore del servizio.
        /// </summary>
        public static string _20 {
            get {
                return ResourceManager.GetString("20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout durante l’autenticazione utente.
        /// </summary>
        public static string _21 {
            get {
                return ResourceManager.GetString("21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente nega il consenso all’invio di dati al SP in caso di sessione vigente.
        /// </summary>
        public static string _22 {
            get {
                return ResourceManager.GetString("22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente con identità sospesa/revocata o con credenziali bloccate.
        /// </summary>
        public static string _23 {
            get {
                return ResourceManager.GetString("23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo di autenticazione annullato dall’utente.
        /// </summary>
        public static string _25 {
            get {
                return ResourceManager.GetString("25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributo Assertion.ID non specificato.
        /// </summary>
        public static string AssertionIdMissing {
            get {
                return ResourceManager.GetString("AssertionIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature differenti.
        /// </summary>
        public static string AssertionSignatureDifferent {
            get {
                return ResourceManager.GetString("AssertionSignatureDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Assertion non trovata.
        /// </summary>
        public static string AssertionSignatureNotFound {
            get {
                return ResourceManager.GetString("AssertionSignatureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Assertion non valida.
        /// </summary>
        public static string AssertionSignatureNotValid {
            get {
                return ResourceManager.GetString("AssertionSignatureNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributi non trovati.
        /// </summary>
        public static string AttributeNotFound {
            get {
                return ResourceManager.GetString("AttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non sono presenti tutti gli attributi richiesti.
        /// </summary>
        public static string AttributeRequiredNotFound {
            get {
                return ResourceManager.GetString("AttributeRequiredNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il FindValue del certificato non può essere nè vuota nè null.
        /// </summary>
        public static string CertificateFindValueNullOrEmpty {
            get {
                return ResourceManager.GetString("CertificateFindValueNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificato non trovato.
        /// </summary>
        public static string CertificateNotFound {
            get {
                return ResourceManager.GetString("CertificateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il certificato non può essere null.
        /// </summary>
        public static string CertificateNull {
            get {
                return ResourceManager.GetString("CertificateNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La password del certificato non può essere nè vuota nè null.
        /// </summary>
        public static string CertificatePasswordNullOrEmpty {
            get {
                return ResourceManager.GetString("CertificatePasswordNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il path del certificato non può essere nè vuoto nè null.
        /// </summary>
        public static string CertificatePathNullOrEmpty {
            get {
                return ResourceManager.GetString("CertificatePathNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La stringa base64 del certificato non può essere nè vuota nè null.
        /// </summary>
        public static string CertificateRawStringNullOrEmpty {
            get {
                return ResourceManager.GetString("CertificateRawStringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile convertire la stringa base64 in ascii.
        /// </summary>
        public static string ConversionBase64Errror {
            get {
                return ResourceManager.GetString("ConversionBase64Errror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} diverso da {1}.
        /// </summary>
        public static string DifferentFrom {
            get {
                return ResourceManager.GetString("DifferentFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in un formato non valido.
        /// </summary>
        public static string FormatNotValid {
            get {
                return ResourceManager.GetString("FormatNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valore InResponseTo non valido.
        /// </summary>
        public static string InResponseToNotValid {
            get {
                return ResourceManager.GetString("InResponseToNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributo Destination della risposta diverso da quello della richiesta.
        /// </summary>
        public static string InvalidDestination {
            get {
                return ResourceManager.GetString("InvalidDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature non valida.
        /// </summary>
        public static string InvalidSignature {
            get {
                return ResourceManager.GetString("InvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssueInstant mancante.
        /// </summary>
        public static string IssueInstantMissing {
            get {
                return ResourceManager.GetString("IssueInstantMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributo Assertion IssueIstant successivo a IssueInstant della richiesta.
        /// </summary>
        public static string IssueIstantAssertionGreaterThanRequest {
            get {
                return ResourceManager.GetString("IssueIstantAssertionGreaterThanRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributo Assertion IssueIstant precedente a IssueInstant della richiesta.
        /// </summary>
        public static string IssueIstantAssertionLessThanRequest {
            get {
                return ResourceManager.GetString("IssueIstantAssertionLessThanRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssueIstant diverso da quello di richiesta.
        /// </summary>
        public static string IssueIstantDifferentFromRequest {
            get {
                return ResourceManager.GetString("IssueIstantDifferentFromRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemento Issuer diverso da EntityID IdP.
        /// </summary>
        public static string IssuerDifferentFromEntityId {
            get {
                return ResourceManager.GetString("IssuerDifferentFromEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributo Format di Issuer diverso.
        /// </summary>
        public static string IssuerFormatDifferent {
            get {
                return ResourceManager.GetString("IssuerFormatDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemento Issuer mancante.
        /// </summary>
        public static string IssuerMissing {
            get {
                return ResourceManager.GetString("IssuerMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemento Issuer non specificato.
        /// </summary>
        public static string IssuerNotSpecified {
            get {
                return ResourceManager.GetString("IssuerNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mancante.
        /// </summary>
        public static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotBefore maggiore della data di ricezione della response.
        /// </summary>
        public static string NotBeforeGreaterThenRequest {
            get {
                return ResourceManager.GetString("NotBeforeGreaterThenRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} non definito.
        /// </summary>
        public static string NotDefined {
            get {
                return ResourceManager.GetString("NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotOnOrAfter precedente alla ricezione della response.
        /// </summary>
        public static string NotOnOrAfterLessThenRequest {
            get {
                return ResourceManager.GetString("NotOnOrAfterLessThenRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} non specificato.
        /// </summary>
        public static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non valido.
        /// </summary>
        public static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il parametro {0} non può essere null.
        /// </summary>
        public static string ParameterCantNull {
            get {
                return ResourceManager.GetString("ParameterCantNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il parametro {0} non può essere ne null ne vuoto.
        /// </summary>
        public static string ParameterCantNullOrEmpty {
            get {
                return ResourceManager.GetString("ParameterCantNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} non valido.
        /// </summary>
        public static string ParameterNotValid {
            get {
                return ResourceManager.GetString("ParameterNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La chiave privata del certificato non è presente.
        /// </summary>
        public static string PrivateKeyNotFound {
            get {
                return ResourceManager.GetString("PrivateKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La referenceUri non può essere nè vuota nè null.
        /// </summary>
        public static string ReferenceUriNullOrWhitespace {
            get {
                return ResourceManager.GetString("ReferenceUriNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion non trovata nella risposta.
        /// </summary>
        public static string ResponseAssertionNotFound {
            get {
                return ResourceManager.GetString("ResponseAssertionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthnResponse non valida.
        /// </summary>
        public static string ResponseNotValid {
            get {
                return ResourceManager.GetString("ResponseNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Response non trovata.
        /// </summary>
        public static string ResponseSignatureNotFound {
            get {
                return ResourceManager.GetString("ResponseSignatureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Response non valida.
        /// </summary>
        public static string ResponseSignatureNotValid {
            get {
                return ResourceManager.GetString("ResponseSignatureNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;url del single signon deve essere valorizzato.
        /// </summary>
        public static string SingleSignOnUrlRequired {
            get {
                return ResourceManager.GetString("SingleSignOnUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie relativo alla sessione di login mancante, e&apos; necessario effettuare una nuova login.
        /// </summary>
        public static string SpidPropertiesNotFound {
            get {
                return ResourceManager.GetString("SpidPropertiesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusCode non valido.
        /// </summary>
        public static string StatusCodeNotValid {
            get {
                return ResourceManager.GetString("StatusCodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status non valido.
        /// </summary>
        public static string StatusNotValid {
            get {
                return ResourceManager.GetString("StatusNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url metadata identity provider non configurato.
        /// </summary>
        public static string UrlMetadataIDPNull {
            get {
                return ResourceManager.GetString("UrlMetadataIDPNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version non valida.
        /// </summary>
        public static string VersionNotValid {
            get {
                return ResourceManager.GetString("VersionNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il documento XML non può essere null.
        /// </summary>
        public static string XmlDocNull {
            get {
                return ResourceManager.GetString("XmlDocNull", resourceCulture);
            }
        }
    }
}
