//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPID.AspNetCore.Authentication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPID.AspNetCore.Authentication.Resources.ErrorLocalization", typeof(ErrorLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato della richiesta non conforme alle specifiche SAML.
        /// </summary>
        internal static string _08 {
            get {
                return ResourceManager.GetString("08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametro Version non presente, malformato o diverso da 2.0.
        /// </summary>
        internal static string _09 {
            get {
                return ResourceManager.GetString("09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID non presente, malformato o non conforme.
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestAuthnContext non presente, malformato o non previsto da Spid.
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssueInstant non presente, malformato o non coerente con l&apos;orario di arrivo della richiesta.
        /// </summary>
        internal static string _13 {
            get {
                return ResourceManager.GetString("13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination non presente, malformata o non coincidente con il gestore delle identità ricevente la richiesta.
        /// </summary>
        internal static string _14 {
            get {
                return ResourceManager.GetString("14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributo IsPassive presente e attualizzato al valore True.
        /// </summary>
        internal static string _15 {
            get {
                return ResourceManager.GetString("15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertionConsumerService non correttamente valorizzato.
        /// </summary>
        internal static string _16 {
            get {
                return ResourceManager.GetString("16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributo Format dell&apos;elemento NameIdPolicy assente o non valorizzato secondo specifica.
        /// </summary>
        internal static string _17 {
            get {
                return ResourceManager.GetString("17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttributeConsumerServiceIndex malformato o che riferisce a un valore non registrato nei metadati di SP.
        /// </summary>
        internal static string _18 {
            get {
                return ResourceManager.GetString("18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticazione fallita per ripetuta sottomissione di credenziali errate..
        /// </summary>
        internal static string _19 {
            get {
                return ResourceManager.GetString("19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente privo di credenziali compatibili con il livello richiesto dal fornitore del servizio..
        /// </summary>
        internal static string _20 {
            get {
                return ResourceManager.GetString("20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout durante l&apos;autenticazione utente..
        /// </summary>
        internal static string _21 {
            get {
                return ResourceManager.GetString("21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente nega il consenso all&apos;invio di dati al SP in caso di sessione vigente..
        /// </summary>
        internal static string _22 {
            get {
                return ResourceManager.GetString("22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente con identità sospesa/revocata o con credenziali bloccate..
        /// </summary>
        internal static string _23 {
            get {
                return ResourceManager.GetString("23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo di autenticazione annullato dall’utente.
        /// </summary>
        internal static string _25 {
            get {
                return ResourceManager.GetString("25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentativo dell&apos;utente di utilizzare una tipologia di identità digitale diversa da quanto richiesto dal SP.
        /// </summary>
        internal static string _30 {
            get {
                return ResourceManager.GetString("30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributo Assertion.ID non specificato.
        /// </summary>
        internal static string AssertionIdMissing {
            get {
                return ResourceManager.GetString("AssertionIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature differenti.
        /// </summary>
        internal static string AssertionSignatureDifferent {
            get {
                return ResourceManager.GetString("AssertionSignatureDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Assertion non trovata.
        /// </summary>
        internal static string AssertionSignatureNotFound {
            get {
                return ResourceManager.GetString("AssertionSignatureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Assertion non valida.
        /// </summary>
        internal static string AssertionSignatureNotValid {
            get {
                return ResourceManager.GetString("AssertionSignatureNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributi non trovati.
        /// </summary>
        internal static string AttributeNotFound {
            get {
                return ResourceManager.GetString("AttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non sono presenti tutti gli attributi richiesti.
        /// </summary>
        internal static string AttributeRequiredNotFound {
            get {
                return ResourceManager.GetString("AttributeRequiredNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il FindValue del certificato non può essere nè vuota nè null.
        /// </summary>
        internal static string CertificateFindValueNullOrEmpty {
            get {
                return ResourceManager.GetString("CertificateFindValueNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificato non trovato.
        /// </summary>
        internal static string CertificateNotFound {
            get {
                return ResourceManager.GetString("CertificateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il certificato non può essere null.
        /// </summary>
        internal static string CertificateNull {
            get {
                return ResourceManager.GetString("CertificateNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La password del certificato non può essere nè vuota nè null.
        /// </summary>
        internal static string CertificatePasswordNullOrEmpty {
            get {
                return ResourceManager.GetString("CertificatePasswordNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il path del certificato non può essere nè vuoto nè null.
        /// </summary>
        internal static string CertificatePathNullOrEmpty {
            get {
                return ResourceManager.GetString("CertificatePathNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La stringa base64 del certificato non può essere nè vuota nè null.
        /// </summary>
        internal static string CertificateRawStringNullOrEmpty {
            get {
                return ResourceManager.GetString("CertificateRawStringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile convertire la stringa base64 in ascii.
        /// </summary>
        internal static string ConversionBase64Errror {
            get {
                return ResourceManager.GetString("ConversionBase64Errror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} diverso da {1}.
        /// </summary>
        internal static string DifferentFrom {
            get {
                return ResourceManager.GetString("DifferentFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in un formato non valido.
        /// </summary>
        internal static string FormatNotValid {
            get {
                return ResourceManager.GetString("FormatNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore generico. Prova ad autenticarti più tardi..
        /// </summary>
        internal static string GenericMessage {
            get {
                return ResourceManager.GetString("GenericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valore InResponseTo non valido.
        /// </summary>
        internal static string InResponseToNotValid {
            get {
                return ResourceManager.GetString("InResponseToNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributo Destination della risposta diverso da quello della richiesta.
        /// </summary>
        internal static string InvalidDestination {
            get {
                return ResourceManager.GetString("InvalidDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature non valida.
        /// </summary>
        internal static string InvalidSignature {
            get {
                return ResourceManager.GetString("InvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssueInstant mancante.
        /// </summary>
        internal static string IssueInstantMissing {
            get {
                return ResourceManager.GetString("IssueInstantMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributo Assertion IssueIstant successivo a IssueInstant della richiesta.
        /// </summary>
        internal static string IssueIstantAssertionGreaterThanRequest {
            get {
                return ResourceManager.GetString("IssueIstantAssertionGreaterThanRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributo Assertion IssueIstant precedente a IssueInstant della richiesta.
        /// </summary>
        internal static string IssueIstantAssertionLessThanRequest {
            get {
                return ResourceManager.GetString("IssueIstantAssertionLessThanRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssueIstant diverso da quello di richiesta.
        /// </summary>
        internal static string IssueIstantDifferentFromRequest {
            get {
                return ResourceManager.GetString("IssueIstantDifferentFromRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemento Issuer diverso da EntityID IdP.
        /// </summary>
        internal static string IssuerDifferentFromEntityId {
            get {
                return ResourceManager.GetString("IssuerDifferentFromEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributo Format di Issuer diverso.
        /// </summary>
        internal static string IssuerFormatDifferent {
            get {
                return ResourceManager.GetString("IssuerFormatDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemento Issuer mancante.
        /// </summary>
        internal static string IssuerMissing {
            get {
                return ResourceManager.GetString("IssuerMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemento Issuer non specificato.
        /// </summary>
        internal static string IssuerNotSpecified {
            get {
                return ResourceManager.GetString("IssuerNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mancante.
        /// </summary>
        internal static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotBefore maggiore della data di ricezione della response.
        /// </summary>
        internal static string NotBeforeGreaterThenRequest {
            get {
                return ResourceManager.GetString("NotBeforeGreaterThenRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} non definito.
        /// </summary>
        internal static string NotDefined {
            get {
                return ResourceManager.GetString("NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotOnOrAfter precedente alla ricezione della response.
        /// </summary>
        internal static string NotOnOrAfterLessThenRequest {
            get {
                return ResourceManager.GetString("NotOnOrAfterLessThenRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} non specificato.
        /// </summary>
        internal static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non valido.
        /// </summary>
        internal static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il parametro {0} non può essere null.
        /// </summary>
        internal static string ParameterCantNull {
            get {
                return ResourceManager.GetString("ParameterCantNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il parametro {0} non può essere ne null ne vuoto.
        /// </summary>
        internal static string ParameterCantNullOrEmpty {
            get {
                return ResourceManager.GetString("ParameterCantNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} non valido.
        /// </summary>
        internal static string ParameterNotValid {
            get {
                return ResourceManager.GetString("ParameterNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La chiave privata del certificato non è presente.
        /// </summary>
        internal static string PrivateKeyNotFound {
            get {
                return ResourceManager.GetString("PrivateKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La referenceUri non può essere nè vuota nè null.
        /// </summary>
        internal static string ReferenceUriNullOrWhitespace {
            get {
                return ResourceManager.GetString("ReferenceUriNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion non trovata nella risposta.
        /// </summary>
        internal static string ResponseAssertionNotFound {
            get {
                return ResourceManager.GetString("ResponseAssertionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthnResponse non valida.
        /// </summary>
        internal static string ResponseNotValid {
            get {
                return ResourceManager.GetString("ResponseNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Response non trovata.
        /// </summary>
        internal static string ResponseSignatureNotFound {
            get {
                return ResourceManager.GetString("ResponseSignatureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Response non valida.
        /// </summary>
        internal static string ResponseSignatureNotValid {
            get {
                return ResourceManager.GetString("ResponseSignatureNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;url del single signon deve essere valorizzato.
        /// </summary>
        internal static string SingleSignOnUrlRequired {
            get {
                return ResourceManager.GetString("SingleSignOnUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie relativo alla sessione di login mancante, e&apos; necessario effettuare una nuova login.
        /// </summary>
        internal static string SpidPropertiesNotFound {
            get {
                return ResourceManager.GetString("SpidPropertiesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusCode non valido.
        /// </summary>
        internal static string StatusCodeNotValid {
            get {
                return ResourceManager.GetString("StatusCodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status non valido.
        /// </summary>
        internal static string StatusNotValid {
            get {
                return ResourceManager.GetString("StatusNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url metadata identity provider non configurato.
        /// </summary>
        internal static string UrlMetadataIDPNull {
            get {
                return ResourceManager.GetString("UrlMetadataIDPNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version non valida.
        /// </summary>
        internal static string VersionNotValid {
            get {
                return ResourceManager.GetString("VersionNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il documento XML non può essere null.
        /// </summary>
        internal static string XmlDocNull {
            get {
                return ResourceManager.GetString("XmlDocNull", resourceCulture);
            }
        }
    }
}
